language: cpp
compiler: gcc
dist: trusty

branches:
  only:
    - master

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - python-pip
      - cppcheck
      - libgmp3-dev
      - libglpk-dev

install: 
  # Libraries
  - sudo python -m pip install numpy scipy matplotlib
  - sudo python -m pip install cpplint pylint
  - bash -e ./configure_libs.sh nauty

before_script:
  - g++ --version
  - python --version
  - pylint --version

script:
  - make all

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
